variables:
  GIT_SUBMODULE_STRATEGY: recursive
  VIVADO_PATH: "/opt/Xilinx/Vivado/2018.3/bin/vivado"
  PROJECT_DIR: "vivado"
  PROJECT_NAME: "ingenious-mips"
  TOP_MODULE_NAME: "ThinPad"

stages:
  - build
  - secoder_record


bitstream:
  stage: build
  tags:
    - vivado
  image: vivado2018:2018.3
  script:
    - env
    - ${VIVADO_PATH} -mode tcl -source ingenious-mips.scripts/build.tcl ${PROJECT_NAME}.xpr

  artifacts:
    paths:
      - ingenious-mips.runs/impl_1/IngeniousMIPS.bit
      - ingenious-mips.runs/impl_1/runme.log
      - ingenious-mips.runs/synth_1/runme.log

sonar-scanner:
  image: harryleafchen/debian-curl-tar
  stage: secoder_record
  tags:
    - secoder
  script:
    - curl -s "http://10.0.0.11/sonar-scanner.tar.gz" -o "/tmp/sonar-scanner.tar.gz"
    - tar -xf "/tmp/sonar-scanner.tar.gz" -C /tmp
    - /tmp/sonar-scanner/bin/sonar-scanner
