# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tfgg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/Dropbox/Work/ingenious-mips/ingenious-mips.cache/wt [current_project]
set_property parent.project_path Z:/Dropbox/Work/ingenious-mips/ingenious-mips.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo z:/Dropbox/Work/ingenious-mips/ingenious-mips.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem Z:/Dropbox/Work/ingenious-mips/ingenious-mips.srcs/sources_1/new/inst_rom.mem
read_verilog -library xil_defaultlib {
  Z:/Dropbox/Work/ingenious-mips/ingenious-mips.srcs/sources_1/new/defines.v
  Z:/Dropbox/Work/ingenious-mips/ingenious-mips.srcs/sources_1/new/ex.v
  Z:/Dropbox/Work/ingenious-mips/ingenious-mips.srcs/sources_1/new/ex_mem.v
  Z:/Dropbox/Work/ingenious-mips/ingenious-mips.srcs/sources_1/new/hilo_reg.v
  Z:/Dropbox/Work/ingenious-mips/ingenious-mips.srcs/sources_1/new/id.v
  Z:/Dropbox/Work/ingenious-mips/ingenious-mips.srcs/sources_1/new/id_ex.v
  Z:/Dropbox/Work/ingenious-mips/ingenious-mips.srcs/sources_1/new/if_id.v
  Z:/Dropbox/Work/ingenious-mips/ingenious-mips.srcs/sources_1/new/ingeniousmips.v
  Z:/Dropbox/Work/ingenious-mips/ingenious-mips.srcs/sources_1/new/inst_rom.v
  Z:/Dropbox/Work/ingenious-mips/ingenious-mips.srcs/sources_1/new/mem.v
  Z:/Dropbox/Work/ingenious-mips/ingenious-mips.srcs/sources_1/new/mem_wb.v
  Z:/Dropbox/Work/ingenious-mips/ingenious-mips.srcs/sources_1/new/pc_reg.v
  Z:/Dropbox/Work/ingenious-mips/ingenious-mips.srcs/sources_1/new/regfile.v
  Z:/Dropbox/Work/ingenious-mips/ingenious-mips.srcs/sources_1/new/ingeniousmips_min_sopc.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ingeniousmips_min_sopc -part xc7a100tfgg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ingeniousmips_min_sopc.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ingeniousmips_min_sopc_utilization_synth.rpt -pb ingeniousmips_min_sopc_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
